# The URL the site will be built for
base_url = "https://uuttff8.github.io"

title = "uuttff8"
compile_sass = true
highlight_code = true
build_search_index = false

theme = "dinkleberg"

taxonomies = [
 {name = "categories"},
 {name = "tags"},
]

[extra]
# blog_logo="/imgs/common/profile.png" #will appear on top header
blog_title="uuttff8" #will appear on top header after logo

## i18n words
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_relative_posts = "Relative Posts"
label_next = "Next"
label_previous = "Previous"
label_page = "Page"
label_of = "of"
label_minutes = "Minutes"


og_image="" # Image that will appear on social media
og_alt_image="" # Alt for og_image
og_site_name="uuttff8" # Site Name for Open Graphic
keywords="swift, rust, blog, uuttff8" # Keywords for SEO

educational_use="knowledge share" # OPTIONAL
copyright_year="2019" # OPTIONAL


## Sidebar automatic links
sidebar = [
    {name = "Social", urls=[
        {name="Telegram", url="https://t.me/rustlangbr"},
        {name="Github", url="https://github.com/rust-br"},
    ]},
    {name = "Contributions!", urls=[
        {name="Contribute!", url="https://github.com/uuttff8"}
    ]}
]